name: release
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      context:
        description: How to correlate status updates.
        required: false
        default: release
      draft:
        description: Is this a draft?
        required: false
        default: "false"
      prerelease:
        description: Is this a prerelease?
        required: false
        default: "false"
      alpine_version:
        description: Which version of Alpine to use for the image. Leave blank for the version in .alpine-version, unless debian_version is supplied.
        required: false
      debian_version:
        description: Which version of Debian to use for the image. Leave blank for the version in .debian-version, unless alpine_version is supplied.
        required: false
      node_version:
        description: Which nodejs version to include in the image. Leave blank for the version in .node-version.
        required: false
      yarn_version:
        description: Which yarn version to include in the image. Leave blank for the version in .yarn-version.
        required: false
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: cancel active workflow runs
        uses: rentpath/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

      - name: check out most recent commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: log inputs
        run: |
          .github/workflows/scripts/log.sh \
            "context:        ${{ github.event.inputs.context }}" \
            "draft:          ${{ github.event.inputs.draft }}" \
            "prerelease:     ${{ github.event.inputs.prerelease }}" \
            "alpine_version: ${{ github.event.inputs.alpine_version }}" \
            "debian_version: ${{ github.event.inputs.debian_version }}" \
            "node_version:   ${{ github.event.inputs.node_version }}" \
            "yarn_version:   ${{ github.event.inputs.yarn_version }}"

      - name: get app token from rossum
        id: rossum
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.ROSSUM_APP_ID }}
          private_key: ${{ secrets.ROSSUM_PRIVATE_KEY }}

      - name: set variables
        id: vars
        run: |
          OWNER=$( echo ${{ github.repository }} | sed -E -e 's/\/.+$//' )
          echo "OWNER=$OWNER" >> $GITHUB_ENV
          echo "::set-output name=owner::${OWNER}"

          REPO=$( echo ${{ github.repository }} | sed -E -e 's/^[^\/]+\///')
          echo "REPO=$REPO" >> $GITHUB_ENV
          echo "::set-output name=repo::${REPO}"

          CONTEXT="${{ github.event.inputs.context || 'release' }}"
          echo "CONTEXT=${CONTEXT}" >> $GITHUB_ENV
          echo "::set-output name=context::${CONTEXT}"

          IMAGE="ghcr.io/${{ github.repository }}"
          if [[ "$REPO" = "ag.js" ]]; then
            IMAGE="ghcr.io/rentpath/agjs"
          fi
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          echo "::set-output name=image::${IMAGE}"

          REF="${{ github.head_ref || github.ref }}"
          echo "REF=${REF}" >> $GITHUB_ENV
          echo "::set-output name=ref::${REF}"

          SHA=$( git rev-parse HEAD )
          echo "SHA=${SHA}" >> $GITHUB_ENV
          echo "::set-output name=sha::${SHA}"

          SHORT_SHA=$( git rev-parse --short HEAD )
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
          echo "::set-output name=short_sha::${SHORT_SHA}"

          ALPINE_VERSION="3.15.4"
          if [[ -n "${{ github.event.inputs.alpine_version }}" ]]; then
            ALPINE_VERSION="${{ github.event.inputs.alpine_version }}"
          elif [[ -n "${{ github.event.inputs.debian_version }}" ]]; then
            ALPINE_VERSION=""
          elif [[ -r .alpine-version ]]; then
            ALPINE_VERSION=$( cat .alpine-version )
          fi
          echo "ALPINE_VERSION=${ALPINE_VERSION}" >> $GITHUB_ENV
          echo "::set-output name=alpine_version::${ALPINE_VERSION}"

          DEBIAN_VERSION="buster-slim"
          if [[ -n "${{ github.event.inputs.debian_version }}" ]]; then
            DEBIAN_VERSION="${{ github.event.inputs.debian_version }}"
          elif [[ -n "${{ github.event.inputs.alpine_version }}" ]]; then
            DEBIAN_VERSION=""
          elif [[ -r .debian-version ]]; then
            DEBIAN_VERSION=$( cat .debian-version )
          fi
          echo "DEBIAN_VERSION=${DEBIAN_VERSION}" >> $GITHUB_ENV
          echo "::set-output name=debian_version::${DEBIAN_VERSION}"

          NODE_VERSION="16.14.0"
          if [[ -n "${{ github.event.inputs.node_version }}" ]]; then
            NODE_VERSION="${{ github.event.inputs.node_version }}"
          elif [[ -r .node-version ]]; then
            NODE_VERSION=$( cat .node-version )
          fi
          echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_ENV
          echo "::set-output name=node_version::${NODE_VERSION}"

          YARN_VERSION="1.22.17"
          if [[ -n "${{ github.event.inputs.yarn_version }}" ]]; then
            YARN_VERSION="${{ github.event.inputs.yarn_version }}"
          elif [[ -r .yarn-version ]]; then
            YARN_VERSION=$( cat .yarn-version )
          fi
          echo "YARN_VERSION=${YARN_VERSION}" >> $GITHUB_ENV
          echo "::set-output name=yarn_version::${YARN_VERSION}"

          ALPINE_FULL_VERSION=""
          if [[ -n "${ALPINE_VERSION}" ]]; then
            ALPINE_FULL_VERSION="alpine-${ALPINE_VERSION}_node-v${NODE_VERSION}_yarn-v${YARN_VERSION}"
          fi
          echo "ALPINE_FULL_VERSION=${ALPINE_FULL_VERSION}" >> $GITHUB_ENV
          echo "::set-output name=alpine_full_version::${ALPINE_FULL_VERSION}"

          DEBIAN_FULL_VERSION=""
          if [[ -n "${DEBIAN_VERSION}" ]]; then
            DEBIAN_FULL_VERSION="debian-${DEBIAN_VERSION}_node-v${NODE_VERSION}_yarn-v${YARN_VERSION}"
          fi
          echo "DEBIAN_FULL_VERSION=${DEBIAN_FULL_VERSION}" >> $GITHUB_ENV
          echo "::set-output name=debian_full_version::${DEBIAN_FULL_VERSION}"

      - name: log variables
        run: |
          .github/workflows/scripts/log.sh \
            "owner:               ${{ steps.vars.outputs.owner }}" \
            "repo:                ${{ steps.vars.outputs.repo }}" \
            "context:             ${{ steps.vars.outputs.context }}" \
            "image:               ${{ steps.vars.outputs.image }}" \
            "ref:                 ${{ steps.vars.outputs.ref }}" \
            "sha:                 ${{ steps.vars.outputs.sha }}" \
            "short_sha:           ${{ steps.vars.outputs.short_sha }}" \
            "node_version:        ${{ steps.vars.outputs.node_version }}" \
            "yarn_version:        ${{ steps.vars.outputs.yarn_version }}" \
            "alpine_version:      ${{ steps.vars.outputs.alpine_version }}" \
            "debian_version:      ${{ steps.vars.outputs.debian_version }}" \
            "alpine_full_version: ${{ steps.vars.outputs.alpine_full_version }}" \
            "debian_full_version: ${{ steps.vars.outputs.debian_full_version }}"

      - name: set context status to "Starting release…"
        uses: rentpath/update-status-action@v1
        with:
          context: "${{ steps.vars.outputs.context }}"
          description: Starting release…
          sha: ${{ steps.vars.outputs.sha }}
          state: pending

      - name: auth with docker
        run: |
          echo ${{ secrets.GHCR_USER_PAT }} | docker login ghcr.io -u ${{ secrets.GHCR_USER_NAME }} --password-stdin

      - name: build Alpine image
        if: steps.vars.outputs.alpine_full_version != ''
        run: |
          docker build \
            -t ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.alpine_full_version }} \
            --build-arg BUILDKIT_INLINE_CACHE \
            --build-arg ALPINE_VERSION="${{ steps.vars.outputs.alpine_version }}" \
            --build-arg NODE_VERSION="${{ steps.vars.outputs.node_version }}" \
            --build-arg YARN_VERSION="${{ steps.vars.outputs.yarn_version }}" \
            --cache-from $CACHE_FROM \
            -f Dockerfile.alpine \
            .
          docker push ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.alpine_full_version }}
        env:
          BUILDKIT_INLINE_CACHE: 1
          CACHE_FROM: "alpine:${{ steps.vars.outputs.alpine_version }}"
          DOCKER_BUILDKIT: 1

      - name: build Debian image
        if: steps.vars.outputs.debian_full_version != ''
        run: |
          docker build \
            -t ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.debian_full_version }} \
            --build-arg BUILDKIT_INLINE_CACHE \
            --build-arg DEBIAN_VERSION="${{ steps.vars.outputs.debian_version }}" \
            --build-arg NODE_VERSION="${{ steps.vars.outputs.node_version }}" \
            --build-arg YARN_VERSION="${{ steps.vars.outputs.yarn_version }}" \
            --cache-from $CACHE_FROM \
            -f Dockerfile.debian \
            .
          docker push ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.debian_full_version }}
        env:
          BUILDKIT_INLINE_CACHE: 1
          CACHE_FROM: "debian:${{ steps.vars.outputs.debian_version }}"
          DOCKER_BUILDKIT: 1

      - name: git tag
        id: release_exists
        shell: bash {0}
        run: |
          git config --global user.email "idg@rentpath.com"
          git config --global user.name "rentpath-plateng"

          ALPINE_RELEASE_EXISTS=""
          if [[ -n "${{ steps.vars.outputs.alpine_full_version }}" ]]; then
            git tag --list "${{ steps.vars.outputs.alpine_full_version }}" | grep -q "${{ steps.vars.outputs.alpine_full_version }}"
            if [[ ! $? ]]; then
              git tag -a ${{ steps.vars.outputs.alpine_full_version }} -m "${{ steps.vars.outputs.alpine_full_version }}"
              git push origin refs/tags/${{ steps.vars.outputs.alpine_full_version }}:refs/tags/${{ steps.vars.outputs.alpine_full_version }}
            else
              ALPINE_RELEASE_EXISTS="true"
            fi
          fi
          echo "ALPINE_RELEASE_EXISTS=${ALPINE_RELEASE_EXISTS}" >> $GITHUB_ENV
          echo "::set-output name=alpine::${ALPINE_RELEASE_EXISTS}"

          DEBIAN_RELEASE_EXISTS=""
          if [[ -z "${{ steps.vars.outputs.debian_full_version }}" ]]; then
            git tag --list "${{ steps.vars.outputs.debian_full_version }}" | grep -q "${{ steps.vars.outputs.debian_full_version }}"
            if [[ ! $? ]]; then
              git tag -a ${{ steps.vars.outputs.debian_full_version }} -m "${{ steps.vars.outputs.debian_full_version }}"
              git push origin refs/tags/${{ steps.vars.outputs.debian_full_version }}:refs/tags/${{ steps.vars.outputs.debian_full_version }}
            else
              DEBIAN_RELEASE_EXISTS="true"
            fi
          fi
          echo "DEBIAN_RELEASE_EXISTS=${DEBIAN_RELEASE_EXISTS}" >> $GITHUB_ENV
          echo "::set-output name=debian::${DEBIAN_RELEASE_EXISTS}"

      - name: release Alpine image
        if: steps.vars.outputs.alpine_full_version != '' && steps.release_exists.outputs.alpine == ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.vars.outputs.alpine_full_version }}
          release_name: ${{ steps.vars.outputs.alpine_full_version }}
          body: "Docker Image: [${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.alpine_full_version }}](https://github.com/orgs/rentpath/packages/container/package/${{ steps.vars.outputs.repo }}) -- `(docker pull ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.alpine_full_version }})`"
          draft: ${{ github.event.inputs.draft || false }}
          prerelease: ${{ github.event.inputs.prerelease || false }}

      - name: release Debian image
        if: steps.vars.outputs.debian_full_version != '' && steps.release_exists.outputs.debian = ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.vars.outputs.debian_full_version }}
          release_name: ${{ steps.vars.outputs.debian_full_version }}
          body: "Docker Image: [${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.debian_full_version }}](https://github.com/orgs/rentpath/packages/container/package/${{ steps.vars.outputs.repo }}) -- `(docker pull ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.debian_full_version }})`"
          draft: ${{ github.event.inputs.draft || false }}
          prerelease: ${{ github.event.inputs.prerelease || false }}

      - if: success()
        name: set context status to "success" with the build version
        uses: rentpath/update-status-action@v1
        with:
          context: "${{ steps.vars.outputs.context }}"
          sha: ${{ steps.vars.outputs.sha }}
          state: success

      - if: cancelled()
        name: set context status to "cancelled"
        uses: rentpath/update-status-action@v1
        with:
          context: "${{ steps.vars.outputs.context }}"
          description: A user or a recent push canceled this build.
          sha: ${{ steps.vars.outputs.sha }}
          state: cancelled

      - if: failure()
        name: set context status to "failure"
        uses: rentpath/update-status-action@v1
        with:
          context: "${{ steps.vars.outputs.context }}"
          description: Build failed. See the 'release' workflow for logs.
          sha: ${{ steps.vars.outputs.sha }}
          state: failure
